<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>TrayGames</AssemblyName>
    <RootNamespace>TrayGames.Launcher</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrayGames.Core\TrayGames.Core.csproj" />
  </ItemGroup>

</Project>
