<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>TrayGame.Tetris</AssemblyName>
    <RootNamespace>TrayGames.Tetris</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TrayGames.Core\TrayGames.Core.csproj" />
  </ItemGroup>

</Project>
