<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>TrayGame.Koi</AssemblyName>
    <RootNamespace>TrayGames.Koi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TrayGames.Core\TrayGames.Core.csproj" />
  </ItemGroup>

</Project>
